# SubNav
menu:
  关于: /2014/aboutme/
subnav:
  #github: "https://github.com/imfycc"
  follow: "https://app.follow.is/share/feeds/57360050735182873"
  jike: "https://web.okjike.com/u/5005922E-4A9D-4197-BE4D-82A6215D9C4C"
  xiaohongshu: "https://www.xiaohongshu.com/user/profile/5b9dd4c026b94a0001bda524"
  weibo-original: "http://weibo.com/u/5263249441"
  apple-email: "mailto:hufy3651@163.com"
  #zhihu: "https://www.zhihu.com/people/hu-yang-11-57/"
  #makers-union: "https://union.zhaodao.ai/#random"
  #sf: "https://segmentfault.com/u/youthink"
  #youthol: "http://www.youthol.cn"
  #rss: "/atom.xml"

author: 方运的博客
description: 天马行空，爱生活，爱Coding

# SEO
seo_keywords: 胡方运,小猿大圣,编程,程序员,个人博客,Youthink,imfycc,Web
seo_description: 小猿大圣的个人博客,胡方运的博客,编程随想

# 底部的备案信息
copyright_date: 2013-2024
beian_info: 胡方运的博客 鲁ICP备15009509号

favicon: "https://static.hufangyun.com/favicon.ico"

#你的头像url
avatar: https://static.hufangyun.com/face-small.png

# 首页左侧边栏背景图片
# 可配置多个 随机挑选一张
leftBackground:
  - https://static.hufangyun.com/hexo/bg1.jpg
  - https://static.hufangyun.com/hexo/bg2.jpg
  - https://static.hufangyun.com/hexo/bg3.jpg
  - https://static.hufangyun.com/hexo/bg4.jpg
  - https://static.hufangyun.com/hexo/bg5.jpg
  - https://static.hufangyun.com/hexo/bg6.jpg

# 展示更新时间
display_updated: true

# Data statistics
baidu_analytics: true
baidu_analytics_code: 279edd956f5d814ddf08af30b654b4c6

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 3b064dc018768ed172b8
gitalk_clientSecret: 403c6f397465f7fa14cfb02668011929102421d1
gitalk_repo: Youthink.github.io
gitalk_owner: Youthink
gitalk_admin: Youthink

console: true
console_color: '#6190e8'
console_config:
  - '\n欢迎访问 https://hufangyun.com ，围观我的博客(づ｡◕‿‿◕｡)づ！\n'
  - '\n本博客使用 %cHexo%c 搭建，博客主题为本人开发的 %chexo-themes-yearn%c ~~~ 🎉🎉🎉 \n\n源码 https://github.com/imfycc/hexo-themes-yearn \n\n如果喜欢可以 star 支持一下 ❤️~\n'
  - '\n扫描下面的二维码，在手机上查看博客！\n'
  - 'https://static.hufangyun.com/blog-url-qrcode-180-180.png'
  - '\n 想知道这个效果如何实现的？博客内搜索 console 彩蛋 🚀 ！\n'


# 长时间未更新的博文显示提醒
overdue_auto_all: false
overdue_remind: 本文最后更新于$day天前，文中所描述的信息可能已发生改变。
